version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.0
    container_name: elk_es
    environment:
     - ES_JAVA_OPTS:"-Des.path.conf=/etc/elasticsearch"
    volumes:
     - ./es_config:/usr/share/elasticsearch/config
     - ./es_data:/usr/share/elasticsearch/data
    networks:
     - logging
  fluentd:
    image: neths/docker-fluentd-es:1.0.0
    container_name: elk_fluentd
    volumes:
     - ./fluentd_config:/fluentd/etc
    environment:
     - FLUENTD_CONF=fluentd.conf
    networks:
     - logging
  kibana:
    image: kibana:5.0.0
    container_name: elk_kibana
    volumes:
     - ./kibana_config/:/opt/kibana/config/
    networks:
     - logging
    ports:
     - 5601:5601

networks:
  logging:
    external:
      name: net_logging
