version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.0
    container_name: elk_es
    command: ["elasticsearch", "-E", "network.host=0.0.0.0"]
    environment:
     - ES_JAVA_OPTS:"-Des.path.conf=/etc/elasticsearch"
    volumes:
     - /home/infra/elk/es_data:/usr/share/elasticsearch/data
    networks:
     - docker_elk
  logstash:
    image: logstash:5.0.0
    container_name: elk_logstash
    command: ["-f", "/etc/logstash/conf.d/"]
    volumes:
     - /home/infra/elk/logstash_config:/etc/logstash/conf.d
    networks:
     - docker_elk
  kibana:
    image: kibana:5.0.0
    volumes:
     - /home/infra/elk/kibana_config/:/opt/kibana/config/
    networks:
     - docker_elk
    ports:
     - 5601:5601     

networks:
  docker_elk:
    driver: bridge
