version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: es
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
     - /home/infra/elk/es_data:/usr/share/elasticsearch/data
     - /home/infra/elk/es_config:/usr/share/elasticsearch/config
