version: '2'

services:
  proxy:
    container_name: reverse_proxy
    image: traefik
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme:/etc/traefik/acme

networks:
  traefik-net:
    external: true
