defaultEntryPoints = ["http","https"]

[web]
  address = ":8080"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "neths.fr"
  watch = true
  exposedbydefault = false
  usebindportip = true
#  swarmmode = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "vacher.michel@gmail.com"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  onDemand = true
#  caServer = "https://acme-staging.api.letsencrypt.org/directory"
